name: Pliki PS1

on:
        paths:
      - '*.ps1'

jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kodu
        uses: actions/checkout@v3

      
      - name: Wypisz zawartość katalogu
        run: ls -la

      - name: Komunikat końcowy
        run: echo "GitHub PS1 Actions działa poprawnie"
